### ISSUE TITLE
CLAIM

### ISSUE THREAD

**Issue by TanuiBwambok** [koechgideon/Prank-Call-App#1]
hey Gideon, you stole my repository,
remove my contact details in the source code. keikas ooh weri

**Comment by koechgideon** [comment]
Haha Sawa chemosi.

**Comment by koechgideon** [comment]
I did not steal it though.

**Comment by TanuiBwambok** [comment]
where did you get it and how,, that's my code

**Comment by s1online** [comment]
> hey Gideon, you stole my repository,
> 
> remove my contact details in the source code. keikas ooh weri

No you scammer! I hired another freelancer
